name: "Build"
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    # Random time each week.
    - cron:  '32 1 * * 3'

jobs:
  build:
    uses: silvenga-docker/building/.github/workflows/publish-github.yaml@master
    secrets: inherit
